CREATE DATABASE bench;

CREATE TABLE IF NOT EXISTS m1 (
  id SERIAL PRIMARY KEY
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE IF NOT EXISTS m2 (
  id SERIAL PRIMARY KEY,
  m1_id BIGINT NOT NULL,
  INDEX m1_id_idx(m1_id)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4;
